import { Injectable } from '@angular/core';
import { MatDialog, MatDialogRef } from '@angular/material';
import { YesOrNoDialogData, YesOrNoDialogComponent } from './yes-or-no/yes-or-no.component';

@Injectable({
  providedIn: 'root'
})
export class YesOrNoService {

  constructor(public dialog: MatDialog) { }

  /** Example usage
   * returns MatDialogRef generated by MatDialog.open();
   * therefore same api applies:
   * DialogService.show(data: YesOrNoDialogData).afterClosed() returns an Observable of type boolean indeicating yes or no
   */
  public show(
    data: YesOrNoDialogData
  ): MatDialogRef<YesOrNoDialogComponent, boolean> {
    const dialogRef = this.dialog;
    if (dialogRef.openDialogs.length > 0) {
      return;
    }

    let widthConfig = '350px';
    if (data && data.width) {
      widthConfig = data.width;
    }
    return dialogRef.open(YesOrNoDialogComponent, {
      width: widthConfig,
      data: data
    });
  }
}
