import { MatDialog, MatDialogRef } from '@angular/material';
import { YesOrNoDialogComponent } from './yes-or-no/yes-or-no.component';
import { YesOrNoDialogData } from './models/dialogData';
export declare class YesOrNoService {
    dialog: MatDialog;
    constructor(dialog: MatDialog);
    /** Example usage
     * returns MatDialogRef generated by MatDialog.open();
     * therefore same api applies:
     * DialogService.show(data: YesOrNoDialogData).afterClosed() returns an Observable of type boolean indeicating yes or no
     */
    show(data: YesOrNoDialogData): MatDialogRef<YesOrNoDialogComponent, boolean>;
}
